### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by suprenant** [Northwestern-Project-Team/Project-1#15]
Format discussion (from Slack):
_Are we required to make a power point presentation for Project 1 or can present our work directly from Jupyter?_
_Either or! Whatever you think will give you the highest quality presentation_

[Presentation deck](https://docs.google.com/presentation/d/1tU4YXINYIqiqSC14s0PRgM-zUYV_OMhVLJgL09DTveQ/)

**Comment by suprenant** [comment]
Picking this up, putting together a presentation deck outline for us..

**Comment by suprenant** [comment]
Linked deck above

**Comment by suprenant** [comment]
OK, made a dent in the linked deck above. We can refine as we do our analysis/visualizations and go along.

**Comment by suprenant** [comment]
From our discussion, we are aiming to all have something in place by noon Saturday so we can run through our presentation together.

**Comment by Lei-Gu** [comment]
updated ppt slides for catagory findings

**Comment by suprenant** [comment]
Nice looks good. We can work to clean up all the slides as discussed later.

**Comment by Lei-Gu** [comment]
Nicely done everyone! We did a great work together!
