### ISSUE TITLE
[spike] Apple Store

### ISSUE THREAD

**Issue by suprenant** [Northwestern-Project-Team/Project-1#20]
From our discussion, @Lei-Gu may take a look at this as time allows.

**Comment by Lei-Gu** [comment]
uploaded "Google and Apple Store.ipynb" for merged datasets. 533 common apps. 

I think when we answer question like" Which categories have the highest number of available apps?"
Comparing with two individual datasets directly can provide better answer than the merged datasets.

However, if we'd like to dive into details about same app in two app store, the merged datasets can be very useful. a interesting fact, from statistical overview, the mean of Rating and Price for same 533 app are different.

**Comment by suprenant** [comment]
Sounds good. Nicely done! 

I went ahead and assigned the issue to you even though it's done so we can know at a glance later who worked on it. Feel free to change if you prefer otherwise.
