### ISSUE TITLE
Filenames/cruft in repo cleaned up

### ISSUE THREAD

**Issue by suprenant** [Northwestern-Project-Team/Project-1#21]
Something we may want to do at some point to keep things easy to find (AppStore v. AppleStore v. Play etc.)

Probably not a big deal but we may want to do this if we start getting confused. Also good practice for if new people came on in the future (or we come back in a year and need help figuring out what's what).

**Comment by Lei-Gu** [comment]
the unused file have been deleted and restored as backups for future use.

**Comment by suprenant** [comment]
Nice thanks @Lei-Gu  !
